### PR TITLE
add script to read in data

### PR DESCRIPTION
**Pull request by ghost**
# Summary

This branch adds a script for reading in data. 

# Please check

- that it works
- that you agree with the style used

# To run

in the console, type `source(here("read_in_data.R"))`.

# thanks

### CODE REVIEW

**Review by thisisalice — CHANGES_REQUESTED** [review]
Hi @thisisbobb 
there are a few issues here. 
1) You haven't added the data.csv file
2) the script name could be more descriptive about what it's doing, like 'read_in_data.R'. 
Thanks.

**Comment by ghost** [comment]
Hi @thisisalice 
Thanks for your feedback! I've renamed my file. 
I don't think data should be tracked by Git because this is sensitive information. As long as you and I have saved the same data in the same location, it should work fine. I've added an Rproj file if this helps. 
Thanks.

**Review by thisisalice — CHANGES_REQUESTED** [review]
Hi @thisisbobb 
That's fine, I agree with you on the data. 
Also, you commit messages don't follow the style guide we agreed. Would you change these please? If you add a feat: or s refactor: at the beginning of the commit message, that should be enough. 
Thanks,

**Review by thisisalice — APPROVED** [review]
looks good! 👍

**Pull request merged**
